rmsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('srm.urls', namespace='srm')),
]

srm/urls.py
from django.conf.urls import url

from srm import views

urlpatterns = [
    url(r'^$', views.get_files),
    url(r'^files/', views.get_files, name='files_list'),
    url(r'^task/create', views.TaskCreate.as_view(), name='task_create'),
    url(r'^tasks', views.TaskListView.as_view(), name='tasks'),
    url(r'^task/(?P<pk>\d+)/$', views.TaskDetailView.as_view(), name='task_details'),
    url(r'^trash/', views.TrashListView.as_view(), name='trash'),
]

srm/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.


class Trash(models.Model):
    path = models.FilePathField(allow_files=False, allow_folders=True, path="/home", recursive=True)
    status = models.CharField(max_length=100, default="")
    recursive = models.BooleanField(default=False)
    interactive = models.BooleanField(default=False)
    directory = models.BooleanField(default=False)
    force = models.BooleanField(default=False)
    verbose = models.BooleanField(default=False)
    silent = models.BooleanField(default=False)
    dry_run = models.BooleanField(default=False)
    name_valid = models.CharField(max_length=20, default="error")

    def __str__(self):
        return self.path


class Task(models.Model):
    name = models.CharField(max_length=100, default="", unique=True)
    trash = models.ForeignKey(Trash)
    rm_file = models.FilePathField(allow_files=True, allow_folders=True, recursive=True, path="/home")
    status = models.CharField(max_length=100, default="")
    recursive = models.BooleanField(default=False)
    interactive = models.BooleanField(default=False)
    directory = models.BooleanField(default=False)
    force = models.BooleanField(default=False)
    verbose = models.BooleanField(default=False)
    silent = models.BooleanField(default=False)
    dry_run = models.BooleanField(default=False)
    name_valid = models.CharField(max_length=20, default="error")

    def __str__(self):
        return self.name

srm/forms.py
from django import forms
from .models import Task


class TaskCreationForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['rm_file','status']

srm/views.py
import os

from django.http import HttpResponseNotFound
from django.shortcuts import render
from django.core.urlresolvers import reverse, reverse_lazy

# Create your views here.
from django.views.generic import CreateView, ListView, DetailView

from srm.forms import TaskCreationForm
from srm.models import Task, Trash


def get_files(request):

    if request.method == 'GET':
        path = '/home'
    elif request.method == 'POST':
        path = request.POST['path']
    else:
        return HttpResponseNotFound('<h1>Page not found</h1>')

    files = []
    for item in os.listdir(path):
        path_to_item = os.path.join(path, item)
        file_rm = {'name': item,
                   'path': path_to_item,
                   'is_dir': os.path.isdir(path_to_item)
                   }
        files.append(file_rm)

    files.sort(key=lambda o: o['name'])
    return render(request, 'srm/files_list.html', {'files': files})


class TaskCreate(CreateView):
    model = Task
    form_class = TaskCreationForm
    template_name = 'srm/tasks/task_create.html'
    success_url = reverse_lazy('srm:files_list')

    def form_valid(self, form):
        form.instance.path = self.request.GET['path']
        print form.instance.path
        return super(TaskCreate, self).form_valid(form)


class TaskListView(ListView):
    model = Task
    template_name = 'srm/tasks/task_list.html'


class TaskDetailView(DetailView):
    model = Task
    template_name = 'srm/tasks/task_detail.html'


class TrashListView(ListView):
    model = Trash
    template_name = 'srm/trash/tash_list.html'

srm/templates/srm/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RmSite</title>

    <!--CSS-->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <!--End CSS-->

</head>
<body>

    <!--Navigation-->
    <nav class="navbar navbar-default">
        <div class="container-fluid ">
        <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                </button>
                <a class="navbar-brand" href="#">SRM</a>
            </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="/tasks ">Tasks</a></li>
                    <li><a href="/trash">Trash</a></li>
                    <li><a href="/files">Files</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/admin"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <!--End Navigation-->
    <div class="content container">
            {% block content %}
            {% endblock %}
    </div>
</body>
</html>

srm/templates/srm/files_list.html
{% extends 'srm/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            <ul class="list-group">
                {% for file in files %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-md-9">
                                {{ file.name }}
                            </div>

                            <div class="col-md-1">
                                {% if file.is_dir %}
                                    <form method='POST' action='/files/'>
                                        {% csrf_token %}
                                        <input type='hidden' name='path' value='{{ file.path }}'>

                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-folder-open" aria-hidden="true"></span>
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                            <div class="col-md-1">
                                <a href="{% url 'srm:task_create' %}?path={{ file.path }}" class="btn btn-sm btn-primary">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                </a>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

{% endblock content %}

srm/templates/srm/tasks/task_create.html
{% extends 'srm/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h1>Create Task</h1>
            <form action="" method="post">
                {% csrf_token %}
                    {{ form.as_p }}
                <button id="submit" type="submit" class="btn btn-lg btn-primary col-md-offset-3">Create</button>
            </form>
        </div>
    </div>

{% endblock content %}

srm/templates/srm/tasks/task_detail.html
{% extends 'srm/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h1>{{ object.name }}</h1>
            <p>File: {{ object.rm_file}}</p>
            <p>Trash: {{ object.trash }}</p>
            <p>Status: {{ object.status }}</p>
        </div>
    </div>

{% endblock content %}

srm/templates/srm/tasks/task_list.html
{% extends 'srm/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h1>Tasks</h1>
                <ul class="list-group">
                    {% for task in object_list %}
                        <li class="list-group-item">
                        <div class="row">
                        <div class="col-md-9">
                            <a href="{% url 'srm:task_details' task.id  %}">{{ task.name }}</a>
                        </div>
                        <div class="col-md-1">
                            <a href="" class="btn btn-sm btn-success">
                                <span class="glyphicon glyphicon-play" aria-hidden="true"></span>
                            </a>
                        </div>
                        </div>
                        </li>
                    {% endfor %}
                </ul>

        </div>
    </div>

{% endblock content %}

srm/templates/srm/trash/tash_list.html
{% extends 'srm/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <h1>Trash List</h1>
                <ul class="list-group">
                    {% for trash in object_list %}
                        <li class="list-group-item">{{ trash.path }}</li>
                    {% endfor %}
                 </ul>

        </div>
    </div>

{% endblock content %}